### ISSUE TITLE
Performance numbers look wrong or possibly backwards

### ISSUE THREAD

**Issue by b4hand** [bhendrickson/safe_arena#1]
From the [README.md](https://github.com/bhendrickson/safe_arena#performance), you have the following listed performance numbers:

> |  | std::unique_ptr + std::vector | abc::arena + gsl::span | speedup |
> | --- | --- | --- | --- |
> | Linux (clang) | 1007 ms | 3143 ms | 3.12x |
> | Windows (msvc) | 1261 ms | 7621 ms | 6.04x |

However, assuming the numbers are actually milliseconds, this would imply that `abc::arena + gsl::span` is actually 3x slower than `std::unique_ptr + std::vector` on clang rather than 3x faster.

**Comment by bhendrickson** [comment]
Good point!

They were backwards.  Also, while cloning this repository to check this, I noticed a few other issues, such as the GSL dependency wasn't getting setup correctly in cmake.

Numbers should now be right. Thanks again.
